### ISSUE TITLE
Trivial: Update GBIF API call

### ISSUE THREAD

**Issue by timrobertson100** [Vizzuality/GeoCAT#3]
Currently GeoCAT is including data GBIF have marked as "geospatially suspicious" which makes GBIF mediated data look poor.  Try Puma concolor which shows records in the sea off Argentina, which GBIF maps will not.

Please update this line as it is incorrectly using the GBIF API:
  https://github.com/Vizzuality/GeoCAT/blob/master/app/controllers/gbif_controller.rb#L14

There are 2 issues:
  1) `isGeoreferenced=true` should be `hasCoordinate=true` 
  2) `coordinateissues=false` should be `hasGeospatialIssue=false`

Here is a working example.  
http://api.gbif.org/v1/occurrence/search?hasCoordinate=true&format=darwin&limit=3&hasGeospatialIssue=false&scientificName=Puma%20concolor

**Comment by timrobertson100** [comment]
Please also note that there are 2829 records returned for Puma concolor within which there are 1846 distinct points.  GeoCAT is showing about a quarter of the records available.

**Comment by simaob** [comment]
Thanks @timrobertson100 we will look into fixing this. Regarding the number of records returned, we currently limit them for the sake of the users machines, but are planning to add a feature to allow people to fetch further records.

**Comment by simaob** [comment]
Issue fixed on staging. We will merge to production later today.
